### ISSUE TITLE
Replace Text "Anxeity Management App" with "SereniFy" at every occurrence in app. 

### ISSUE THREAD

**Issue by Amna-Hassan04** [Amna-Hassan04/Serenity-Guide#10]
Their are a few places in app where it is named at "Anxeity Management app" change it to "SereniFy".

**Comment by RudraKumarSharma** [comment]
Please assign me this task i want to contribute!!

**Comment by arhaanarif** [comment]
Please assign me this task i want to contribute

**Comment by Amna-Hassan04** [comment]
@arhaanarif  I have assigned the task to Rudra on a first come - first served basis. please ask to be assigned some other task that is not yet claimed by someone else.

**Comment by RudraKumarSharma** [comment]
@Amna-Hassan04 the repo is missing the package.json file please look into this
![Screenshot 2024-10-02 at 12 37 52 AM](https://github.com/user-attachments/assets/65bd8bf6-64c3-4bdf-b08b-c5d17c5b554b)

**Comment by RudraKumarSharma** [comment]
@Amna-Hassan04 I'm not able to install npm in the serenity-guide folder due to this please help

**Comment by RudraKumarSharma** [comment]
The following error is given on installing npm:
![Screenshot 2024-10-02 at 1 20 31 AM](https://github.com/user-attachments/assets/57d256dd-91d7-4460-9c76-e78e4ac304b8)

**Comment by SaanyaGarg5** [comment]
you can assign that task to me..

**Comment by sid7219** [comment]
pls assign this task to me

**Comment by RudraKumarSharma** [comment]
is anyone else is able to run the application please tell?? ASAP

**Comment by Amna-Hassan04** [comment]
@RudraKumarSharma it runs with "streamlit run app.py". for installing packages you will run command "pip install"

**Comment by Amna-Hassan04** [comment]
@RudraKumarSharma sorry for the confusion the read me file. we are using streamlit in this app so dont to use npm anywhere.

**Comment by RudraKumarSharma** [comment]
yes thankyou
