### ISSUE TITLE
[FEATURE] - Make a "Resource" Page

### ISSUE THREAD

**Issue by shivi13102** [Amna-Hassan04/Serenity-Guide#104]
### Feature Title

The Resources tab offers a curated collection of articles, guides, and self-care tips to support users' mental health and wellness.

### Problem Statement

The Resources tab solves the problem of limited access to reliable mental health information by providing users with expert-curated articles, guides, and self-care tips, making it easier for them to find support and learn effective wellness strategies.

### Proposed Solution

I will solve this problem by adding these feature:
1. Mental Health Articles: A collection of articles and blog posts written by mental health professionals and wellness coaches.
2. Self-Care Tips: Advice on creating self-care routines, managing stress, and fostering positivity.
3. Guides & E-books: Downloadable content on topics like building resilience, practicing gratitude, or coping with stress.
4. Podcast/Audio Library: Short audio sessions on mental health topics like overcoming anxiety, building self-esteem, and more.

**Comment by Amna-Hassan04** [comment]
@shivi13102 yes you can work on this. do make sure that the overall aesthetic of your work matches the aesthetics of the project. attach all the screenhsots / video recordings of the completed features when making a PR

**Comment by Amna-Hassan04** [comment]
@shivi13102 I am labeling this as level 3 for now but depending on the quality of the PR I might change this.

**Comment by Hafsa-shoaib989** [comment]
@Amna-Hassan04  Can you please assign this issue to me?
