### ISSUE TITLE
[FEATURE] - Create an FAQs Page 

### ISSUE THREAD

**Issue by BhaktiMore18** [Amna-Hassan04/Serenity-Guide#105]
### Feature Title

Add FAQs Page to Enhance User Support on SereniFi.

### Problem Statement

Users seeking mental health information often struggle to find quick answers due to the absence of a centralized FAQs page on our website. This lack of accessible information can lead to confusion and increased inquiries to our support team. Creating an FAQs page is crucial to improve user experience and promote mental health awareness.

### Proposed Solution

I would like to propose the addition of an FAQs (Frequently Asked Questions) page to  This pathe serenity guide. That would serve as a valuable resource for users seeking quick answers to common questions related to mental health services, resources, and support.

I would like to work on the same, can assign this to me?

**Comment by BhaktiMore18** [comment]
Would you assign this task to me, so that I can start working on it.

**Comment by Amna-Hassan04** [comment]
@BhaktiMore18 yes u can start working on this. assigning u the task. im assigning u level 2 label for now but this could change depending on the quality of your PR,

**Comment by BhaktiMore18** [comment]
Hey! I have created a PR regarding this issue, kindly check it and let me know if any improvements are required! @Amna-Hassan04
