### ISSUE TITLE
[FEATURE] - Greetings and Label assignment Workflow

### ISSUE THREAD

**Issue by decodingafterlife** [Amna-Hassan04/Serenity-Guide#106]
### Feature Title

Automated Greetings and Label assignment Workflow

### Problem Statement

Sometimes a large number of issues and features may be added by open-source contributors and users. This may lead to the admins being overwhelmed to add labels, allocate and handle all of the issues raised. The solution focuses on automating some part of these process so that admins can focus only on the important that need their attention.

### Proposed Solution

I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

There will be another GitHub workflow named Auto-Label which would scan the title of the raised issue and assign appropriate labels. Specific labels or other requirements suggested by the admins can be integrated in this.

### Additional Context

I wish to contribute to this through hacktoberfest and gssoc-ext. Let me know if you have any suggestions.

**Comment by Amna-Hassan04** [comment]
@decodingafterlife We already have this feature.
