### ISSUE TITLE
[FEATURE] - Movie Recommendation System on the basis of emotion 

### ISSUE THREAD

**Issue by Amanjayswal500** [Amna-Hassan04/Serenity-Guide#111]
### Feature Title

Movie Recommendation System on the basis of emotion 

### Problem Statement

Many people struggle to find movies that support their mental health, often leading to unsuitable or triggering content.

### Proposed Solution

A movie recommendation system that suggests films based on users’ emotional states and preferences to promote mental well-being.

### Alternatives Considered

Generic movie recommendation algorithms without emotional filtering.
User-based manual movie selection based on public reviews.
Counseling-based recommendations from professionals.

### Additional Context

The platform will use sentiment analysis, mood-based tagging, and mental health resources to ensure appropriate content suggestions for diverse emotional needs.

![Screenshot 2024-10-10 111234](https://github.com/user-attachments/assets/35ec8aef-863f-4075-964f-693679c3c0ec)

after clicking link
![Screenshot 2024-10-10 111310](https://github.com/user-attachments/assets/d9be8624-3ae2-46dd-a9f3-7121a2af9478)

**Comment by Amanjayswal500** [comment]
@Amna-Hassan04 please assign this issue to me

**Comment by Amna-Hassan04** [comment]
@Amanjayswal500 for now I dont think this is a need for this feature.
