### ISSUE TITLE
[BUG] - Blue Link Visibility Issue 

### ISSUE THREAD

**Issue by Rahul-AkaVector** [Amna-Hassan04/Serenity-Guide#112]
### Bug Title

Blue Links Visibility Issue 

### Description

There is a visibility issue with blue-colored links on the game page due to a background color change to blue, making the links difficult to see.

### Steps to Reproduce

1. Go to the website.
3. Click on the "Game" button.
4. Observe that the links are displayed in blue, making them blend with the background.

### Expected Behavior

The links should either be placed inside a button or displayed in a different color to ensure they are visible and distinguishable from the background.

### Environment

Operating System: Windows (All Versions) , Browsers: Chrome, Edge

### Additional Context

https://github.com/user-attachments/assets/d4bb8316-4f10-489b-9cca-6583daf54c17

@Amna-Hassan04

**Comment by sociallyencrypted** [comment]
I'd like to fix this! Please assign this to me

Name: Mehul Arora
Contributing at: GSSoc'24 Ext

**Comment by Amna-Hassan04** [comment]
@Rahul-AkaVector assigning u the issue.

**Comment by Amna-Hassan04** [comment]
@sociallyencrypted tasks are assigned on a first come , first served basis.

**Comment by Rahul-AkaVector** [comment]
> @Rahul-AkaVector assigning u the issue.

Thank you!
