### ISSUE TITLE
[FEATURE] - Embed Spotify Playlists for Soothing Sounds Using iFrame API

### ISSUE THREAD

**Issue by ChitteshKumar** [Amna-Hassan04/Serenity-Guide#113]
### Feature Title

Embed Spotify Playlists for Soothing Sounds Using iFrame API

### Problem Statement

Currently, users on our platform  have limited ability to listen to soothing sounds directly from our interface. This is a missed opportunity to enhance user experience by integrating background sounds, music, or meditative playlists that could be beneficial for relaxing while browsing.

Without embedded audio, users are forced to switch between our platform and external music sources, which could distract them from fully engaging with our content.

### Proposed Solution

I propose embedding Spotify playlists of soothing sounds directly on our platform using Spotify's iFrame API. This would allow users to play, pause, and control music without leaving the platform, creating a seamless and relaxing experience. This integration will help in creating a more calming and focused environment for users, improving overall engagement and satisfaction with our platform.

Expected Outcome:

Enhanced user experience with embedded soothing sounds.
Increased time spent on the platform due to a more relaxing and focused environment.
Reduction in the need for users to switch between applications for music.

### Alternatives Considered

There are two more ways to embed Spotify playlists given in the developer documentation from Spotify, I may use them if needed.

**Comment by ChitteshKumar** [comment]
Hi @Amna-Hassan04 , can you assign this to me.

**Comment by Amna-Hassan04** [comment]
@ChitteshKumar Sure, assigning u the issue. while making the PR do include all the relevant screen recording/screenshots.

**Comment by ChitteshKumar** [comment]
thank you for assigning me this issue. I am working on this right away. thank you. will require 3-4 days

**Comment by ChitteshKumar** [comment]
Hi @Amna-Hassan04 , I have completed this task and requested a PR. Kindly have a look at the PR and provide your feedback. Also if I need to change anything in the documentation. Thank you 
Regards
