### ISSUE TITLE
[FEATURE] - Adding A Speaker

### ISSUE THREAD

**Issue by Mandy1200** [Amna-Hassan04/Serenity-Guide#127]
### Feature Title

Adding Soothing Sounds 

### Problem Statement

As this is website to Feel Calm, Centered, and Peaceful we need have some sound effects while strolling the web  like sound effects of forest , night sky , bird chirping and etc...

### Proposed Solution

I will add a speaker button , using with python ( for backend) i will use the musics and Html , Js (for frontend) for toggling the funtion of speaker

**Comment by Amna-Hassan04** [comment]
@Mandy1200 we already have the sound feature + we are also integrating spotify playlists so no need for this rigth now.
