### ISSUE TITLE
In the Read Me File: Fix the wrong link in Contributer Table and change the table to look like the attached sample. 

### ISSUE THREAD

**Issue by Amna-Hassan04** [Amna-Hassan04/Serenity-Guide#13]
1. Change the table to look like this. 
![image](https://github.com/user-attachments/assets/c4f7cfda-d9a5-459e-9d60-f5536a430673)

2. In the last 2 contributers images the links are swapped by mistake, assign the pic to the correct profile.

**Comment by Ayush07571** [comment]
Hey, I am a beginner but know a bit of frontend and I can try to solve your issue. So I request you to give a try and provide me with the permission to work on this issue.

**Comment by apoorvxgoyalx** [comment]
@Amna-Hassan04 , please assign me this issue , i can fix this easily

**Comment by Amna-Hassan04** [comment]
I am assigning to both of you bcz one of u is not sure if he can complete it whoever gets done  please make a pull request, and add the screenshot of your work too.
