### ISSUE TITLE
[FEATURE] - Check if while making a PR contributer has pulled all the latest commits from the repository. 

### ISSUE THREAD

**Issue by Amna-Hassan04** [Amna-Hassan04/Serenity-Guide#134]
### Feature Title

PR should have latest version of the project 

### Problem Statement

I see this problem that some contributers do not use the latest version of the project so when their PR gets merged it overwrites something else. 

### Proposed Solution

Implement a Github action that checks if the made PR or fork of the contributer has the latest version of the project. meaning all teh commits have been pulled from the user. 

### Alternatives Considered

If their is a better solution do plz contribute it the above solution i wrote is just a sample if it can be implemented easily.

**Comment by rishikaa1** [comment]
@Amna-Hassan04 hey! i would like to work on this issue.

**Comment by Kajalkansal30** [comment]
![Screenshot 2024-10-15 004018](https://github.com/user-attachments/assets/40cd49c4-63a8-4d62-b0ed-d506345d9760)
Encourage contributors to ensure their branches are up to date before submitting a PR.

Implementation:

Create a pull request template that outlines the steps contributors should take before submitting their PRs, including:
Pulling the latest changes from the main branch.
Rebasing or merging their branch with the latest changes.
Running tests to ensure compatibility.

Use Cases
New Contributor Onboarding: When a new contributor creates their first PR, the action will ensure they are aware of the need to keep their branch up to date, thereby reducing potential issues.

Ongoing Development: For active contributors working on features or bug fixes over several days, this action will prompt them to periodically sync with the main branch, helping them avoid merge conflicts at the time of submission.

Integration Testing: Before running any automated tests in the CI pipeline, this action will confirm that the code being tested is based on the most recent version of the project, ensuring the tests are relevant and accurate.

 I would like to express my interest in addressing the issue of ensuring contributors are using the latest version of the project before merging their pull requests.

**Comment by Kajalkansal30** [comment]
@Amna-Hassan04 please assign this issue to me.

**Comment by Amna-Hassan04** [comment]
@Kajalkansal30 yes we can add this but this is just for them to read and tick right, many contributers might not follow these steps and then i have to manually ask all of them to pull the latest changes and the PR gets delayed isnt their a way to get it checked automatically if the PR uses the latest version of the repo.

**Comment by RhiyaBhat** [comment]
please assign this issue to me

**Comment by RhiyaBhat** [comment]
I can create a file in the GitHub workflow. The workflow will fetch both the main and the PR branch to compare if the PR branch is up-to-date with the latest commits from the base.

**Comment by Amna-Hassan04** [comment]
@RhiyaBhat Yes this is what I want, you can start working on this.
