### ISSUE TITLE
[FEATURE] - Adding Asynchronous Support for app.py

### ISSUE THREAD

**Issue by smog-root** [Amna-Hassan04/Serenity-Guide#139]
### Feature Title

asyncio

### Problem Statement

If a Python file does not have asynchronous support (i.e., it doesn't use async and await keywords, or libraries designed for asynchronous programming like asyncio), it will execute in a synchronous manner.

### Proposed Solution

Assign This to me with a gssoc-ext with level3 , hacktoberfest-accepted labels!

**Comment by Amna-Hassan04** [comment]
@smog-root from the title of this issue or the description I dont understand how this will he helpful for this project. if you want to disscuss this further make a disscussions post plz.
