### ISSUE TITLE
Add Greeting Bot

### ISSUE THREAD

**Issue by KiranBaliga** [Amna-Hassan04/Serenity-Guide#14]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested!

**Comment by Amna-Hassan04** [comment]
sure, and please in that message add what I just posted in the announcements channel in the Discussions tab.

**Comment by KiranBaliga** [comment]
@Amna-Hassan04 Please review the PR. Please add labels to the PR as well. Thanks a bunch.

**Comment by SaanyaGarg5** [comment]
you can assign that task to me..

**Comment by alpha597** [comment]
you can assign this task to me , for gssoc 2024 ext
