### ISSUE TITLE
[FEATURE] - Better navbar

### ISSUE THREAD

**Issue by Saaarthak0102** [Amna-Hassan04/Serenity-Guide#148]
### Feature Title

Navbar enhancement

### Problem Statement

Will imporve the interface of navbar

### Proposed Solution

better design

**Comment by RounitSrivastava** [comment]
I want to do this task

**Comment by Pranathi71** [comment]
I would like to contribute to navbar enhancement ...Could you please assign it to me..?
@Amna-Hassan04

**Comment by Amna-Hassan04** [comment]
@Saaarthak0102 do show the navbar first here to me before making a PR.

**Comment by Saaarthak0102** [comment]
> @Saaarthak0102 You can work on this, do show the navbar first here to me before making a PR.

sure

**Comment by Saaarthak0102** [comment]
![image](https://github.com/user-attachments/assets/d6774d3d-fa06-47f0-85a3-33a3e0f41d4f)

New navbar added, please review @Amna-Hassan04
