### ISSUE TITLE
Documentation - Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Nikhil0-3** [Amna-Hassan04/Serenity-Guide#150]
### Feature Title

contributing.md

### Problem Statement

Without a CONTRIBUTING.md file, potential contributors may not know how to contribute effectively. This could lead to inconsistencies in contributions and confusion among contributors.

.

### Proposed Solution
Adding the following topics - 
Project Overview
Getting Started
Welcome, Contributors
Contribution Guidelines
Technologies Used
How to Submit a Pull Request
Issue Report Process
Community and Communication
Project Structure
Looking for Ideas?
Join the Mission!
If any further changes required please let me know.

**Comment by tanu91112** [comment]
@Amna-Hassan04
I came across the issue about adding the CONTRIBUTING.md file and would love to take the lead in resolving it.. Could I have the opportunity to work on this issue plz ?

**Comment by tanu91112** [comment]
@Amna-Hassan04 ,
 I had Created a new file called CONTRIBUTING.md in the root of the project.
Added guidelines about:
1). How to fork and clone the repository.
2).Branch naming conventions.
3).Code style and testing guidelines.
4).How to submit pull requests (PRs) and communicate with maintainers.  

  if you assign me with this task so i will send you a pull request.

**Comment by Nikhil0-3** [comment]
Please assign this issue to me.I would like to work on that.

**Comment by Amna-Hassan04** [comment]
@Nikhil0-3 you can work on this but first u will have to calculate if teh total contributions related to documentation havent reached 150 points which i suppose they have.

**Comment by Ricky2054** [comment]
Kindly assign me this issue

**Comment by SparshKhanna0001** [comment]
@Nikhil0-3 why this is still an open issue?

**Comment by SparshKhanna0001** [comment]
@Nikhil0-3 why this is still an open issue?
@Amna-Hassan04

**Comment by SparshKhanna0001** [comment]
@Nikhil0-3 why this is still an open issue?
@Amna-Hassan04

**Comment by SparshKhanna0001** [comment]
@Nikhil0-3 why this is still an open issue?
@Amna-Hassan04
