### ISSUE TITLE
[FEATURE] - navagation bar should be updated

### ISSUE THREAD

**Issue by Dhruvi-tech** [Amna-Hassan04/Serenity-Guide#151]
### Feature Title

navagation

### Problem Statement

very old

### Proposed Solution

by changing the code

**Comment by RounitSrivastava** [comment]
I want to do this task

**Comment by Pranathi71** [comment]
I would like to contribute to navbar enhancement . could you please assign it to me..?
@Amna-Hassan04

**Comment by Amna-Hassan04** [comment]
@Dhruvi-tech someone else was already working on this and has made a PR. this is a duplicate issue.
