### ISSUE TITLE
[FEATURE] - Daily Affirmations Widget

### ISSUE THREAD

**Issue by sanchitc05** [Amna-Hassan04/Serenity-Guide#154]
### Feature Title

Daily Affirmations Widget

### **Daily Affirmations Widget**

Users of the SereniFi app seek effective ways to enhance their mental well-being and maintain a positive mindset. However, many users may find it challenging to engage consistently with the app without regular prompts or reminders. The absence of a feature that delivers daily motivational content limits users' opportunities for positive reinforcement and may hinder their journey toward mental tranquility. 

To address this issue, the Daily Affirmations Widget will provide users with fresh, uplifting affirmations every day, encouraging them to engage with the app regularly. This feature aims to foster a habit of positivity and mindfulness, ultimately contributing to improved emotional resilience and overall well-being.

### Proposed Solution

**Summary**:  
We propose the addition of a **Daily Affirmations Widget** to the SereniFi app. This feature aims to enhance user engagement and promote mental well-being through positive reinforcement.

---

**Description**:  
The Daily Affirmations Widget will display a new positive affirmation daily or at a user-defined interval. Users can choose from different themes such as confidence, relaxation, and productivity. The widget will refresh automatically and allow users to receive push notifications for daily affirmations.

---

**Benefits**:
- **Encourages Consistency**: Regular interaction with the widget will help keep users engaged with the app daily.
- **Boosts Mental Well-being**: Positive affirmations can improve users' emotional resilience and motivation, enhancing their overall experience with the app.
- **User Retention**: By providing valuable content that users can incorporate into their daily routine, we can increase the likelihood of users continuing to use the app.

---

**Acceptance Criteria**:
1. Users should see a new affirmation each day or upon refreshing the widget.
2. Users can select themes for their affirmations (e.g., confidence, relaxation).
3. Users should have the option to enable push notifications for daily affirmations.
4. Affirmations should be stored in the database and can be personalized based on user preferences.
5. The widget should be visually appealing and user-friendly, integrating seamlessly into the existing UI.

---

### **Tech Stack Suggestions for Web**:
- **Frontend**: 
  - **React**: For building the user interface and managing component states.
  - **CSS/SCSS**: For styling the widget and ensuring a visually appealing design.

- **Backend**: 
  - **Node.js** with **Express**: To create a RESTful API for managing user preferences and delivering affirmations.

- **Database**: 
  - **Firebase Firestore** or **MongoDB**: For storing user data, affirmation preferences, and managing daily content.

- **Push Notifications**: 
  - **Firebase Cloud Messaging (FCM)**: For sending daily affirmation notifications to users.

- **Scheduling/Automation**: 
  - **Node.js Cron Jobs** or **Firebase Cloud Functions**: For automating the daily refresh of affirmations.

---

> **Please assign this issue to me, I'll be more than happy to work on such a mindful project.**

### Alternatives Considered

N/A

### Additional Context

This feature aligns perfectly with SereniFi’s mission to help users achieve mental tranquility and enhance their well-being, providing both immediate and long-term benefits.

**Comment by Amna-Hassan04** [comment]
@sanchitc05 This is a python app using streamlit, how will u integrate react with it?

**Comment by sanchitc05** [comment]
@Amna-Hassan04 Streamlit has a feature called st.components.v1 that allows you to integrate custom React components into your Streamlit application.
