### ISSUE TITLE
[FEATURE] -  Adding Exception Handling & logging

### ISSUE THREAD

**Issue by P4R1H** [Amna-Hassan04/Serenity-Guide#163]
### Feature Title

Exception handling and logging

### Problem Statement

Will Add comprehensive logging and exception handling to report errors and make it easier to troubleshoot for future contributors/developers

### Proposed Solution

I would like to work on this issue, Would appreciate it if assigned.

**Comment by Amna-Hassan04** [comment]
@P4R1H yes u can work on this.

**Comment by P4R1H** [comment]
Added logging, common exceptions and a global handler for uncaught exceptions!

![image](https://github.com/user-attachments/assets/9234c324-93c6-4244-a456-a48320d221ce)

**Comment by P4R1H** [comment]
#204 https://github.com/Amna-Hassan04/Serenity-Guide/pull/204

Please accept it before 11:59 if possible after reviewing
