### ISSUE TITLE
[FEATURE] - Add GitHub Workflow for Auto-Closing Similar Issue Requests

### ISSUE THREAD

**Issue by aditiverma-21** [Amna-Hassan04/Serenity-Guide#167]
### Feature Title

Add GitHub Workflow for Auto-Closing Similar Issue Requests

### Problem Statement

Duplicate issues

### Proposed Solution

Implement a GitHub workflow that automatically detects and closes duplicate or similar issue requests. The workflow should:

Utilize a bot or script to compare new issues against existing ones.
Automatically flag or close issues with matching titles, descriptions, or keywords.
Provide a comment linking the user to the original issue for reference.
Ensure the workflow runs on issue creation to streamline project management.

**Comment by aditiverma-21** [comment]
@Amna-Hassan04 Please check this and kindly assign

**Comment by Amna-Hassan04** [comment]
@aditiverma-21 I have seen some people implement this but this sometimes just closes issues that have similar but different functionalities or so. some other project maintainers have had many problems with this so I dont think we should implement this for now.
