### ISSUE TITLE
Feature Addition: Personalized Anxiety Management

### ISSUE THREAD

**Issue by Sagar2006** [Amna-Hassan04/Serenity-Guide#17]
Hello,

I have been working on enhancing the SereniFi project by implementing a Personalized Anxiety Management feature. Below are the key changes I made:

Summary of Changes:
Personalized Anxiety Management Feature:
Added a new section that allows users to input their mood, feelings, stress level, and any recent events contributing to their anxiety.
Implemented an AI-based response using the Anthropic API to provide tailored recommendations based on user inputs.

Documentation Changes:
I will update the documentation to reflect the new Personalized Anxiety Management feature.

Additional Information:
File Updated: app.py
Testing Inputs: Provided sample inputs for the new feature for testing purposes.
I kindly request that you assign this task to me. Thank you for your support!

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gssoc and hacktoberfest...

**Comment by Amna-Hassan04** [comment]
@Sagar2006 Dont we already have all this implemented. with the PR attach the screenshot of every feature how it was before and how you have changed it. and in future when proposing a new feature first you have to disscuss it with making a post  in discussions tab.

**Comment by Sagar2006** [comment]
Apologies for not discussing the feature beforehand. I'll make sure to follow the process by posting in the discussions tab for any new proposals moving forward. I'll also attach the required screenshots of the before and after changes in my PR. Thanks for your guidance!

**Comment by Amna-Hassan04** [comment]
@Sagar2006 sure no problem
