### ISSUE TITLE
[FEATURE] - Adding Contributors page

### ISSUE THREAD

**Issue by Saaarthak0102** [Amna-Hassan04/Serenity-Guide#176]
### Feature Title

Add Contributions Page

### Problem Statement

Will create a new page displaying all the contributors

### Proposed Solution

Will add it to Navbar too!

**Comment by rafiya2003** [comment]
please assign me this issue

**Comment by Saaarthak0102** [comment]
please assign the issue! @Amna-Hassan04

**Comment by Amna-Hassan04** [comment]
@Saaarthak0102 I havent planned this rigth now, plus I guess we have reached our limit of 150 points of no-code contributions.

**Comment by Saaarthak0102** [comment]
> @Saaarthak0102 I havent planned this rigth now, plus I guess we have reached our limit of 150 points of no-code contributions. 

Ohkk! Please merge my another PR issue #148 😅
