### ISSUE TITLE
Add table of contents to the readme file

### ISSUE THREAD

**Issue by T-Fathima** [Amna-Hassan04/Serenity-Guide#178]
### Feature Title

Add table of contents to the readme file

### Problem Statement

Currently the readme file lacks the table of contents section.

### Proposed Solution

I would to propose to add it for better readability and user experience.

**Comment by Amna-Hassan04** [comment]
@T-Fathima We have had a lot of no-code contributions now I believe it has reached its 150 point limit. so we cant do more documentation related contributions anymore.
