### ISSUE TITLE
🚀 Automate Connections with GitHub Actions!

### ISSUE THREAD

**Issue by amiya-cyber** [Amna-Hassan04/Serenity-Guide#181]
### Feature Title

🚀 Automate Connections with GitHub Actions!

### Problem Statement

absence of workflows

### Proposed Solution

We can implement github workflows for the following things:

Auto comment on issue Closed and Opened
Auto comment on PR mergs
Auto comment on PR raises
Using this workflows makes you'r repo more interactive !

**Comment by Amna-Hassan04** [comment]
@amiya-cyber This has already been implemented.
