### ISSUE TITLE
[BUG] - website not working

### ISSUE THREAD

**Issue by amanver45** [Amna-Hassan04/Serenity-Guide#184]
### Bug Title

some  error in code

### Description

website is nog opening

### Steps to Reproduce

s

### Expected Behavior

s
![Uploading Screenshot 2024-10-28 194625.png…]()

### Environment

s

**Comment by SatyamSingh8306** [comment]
can you assign me this issue i want to work on it.

**Comment by Amna-Hassan04** [comment]
@SatyamSingh8306 your screenshot is not visible.

**Comment by Amna-Hassan04** [comment]
@SatyamSingh8306 You can work on this.

**Comment by Amna-Hassan04** [comment]
@SatyamSingh8306 @amanver45 since this is an important issue and you both seem to have commented on the same time I will assign you both, I will merge the PR of Whoever does this first.

**Comment by amanver45** [comment]
@Amna-Hassan04 check my pr #188
