### ISSUE TITLE
adding the feature to scroll back to the top

### ISSUE THREAD

**Issue by ShrishtiSingh26** [Amna-Hassan04/Serenity-Guide#22]
I wish to add the feature to scroll back to the top of the page as it enhances the navigation

please assign this issue under gssoc-ext and hacktoberfest labels

**Comment by SHRAVANIc01** [comment]
i can help you with this, please assign this issue to me under gssoc-ext. [ @Amna-Hassan04 ]

**Comment by SaanyaGarg5** [comment]
you can assign that task to me..

**Comment by ShrishtiSingh26** [comment]
Will be more happy if you assign the issue to the person who raised it? Therefore Please assign the issue to me so that I can contribute successfully.

**Comment by Amna-Hassan04** [comment]
@SaanyaGarg5 @SHRAVANIc01 tasks are assigned on the basis of first come and first serve basis

**Comment by Amna-Hassan04** [comment]
@ShrishtiSingh26 assigning u the task, please attach the screenshot of your work with when making pull request

**Comment by aryy8** [comment]
I can also work on it

**Comment by ShrishtiSingh26** [comment]
@Amna-Hassan04 I have created a PR and resolved the issue #22
Thank you!
