### ISSUE TITLE
Adding images and instructions of Yoga poses for diff anxiety levels and breathing exercises

### ISSUE THREAD

**Issue by Pujitha254** [Amna-Hassan04/Serenity-Guide#27]

**Comment by Pujitha254** [comment]
hey @Amna-Hassan04 !! I really like your thought behind this website. I really wanted to add yoga poses and breathing exercises with time and sound like "INHALE" ,"EXHALE" ..........Take a look here for better understanding
![image](https://github.com/user-attachments/assets/4bc49f5b-16cc-4b44-82fc-bf84c40961e9)

**Comment by Amna-Hassan04** [comment]
@Pujitha254 make a discussions post for this first with the relevant screenshot, and proper features etc. also with all the material you are going to add.

**Comment by Pujitha254** [comment]
ok ....i will definitely share all those things but please don't close this from issues
