### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by priyanshaggarwal001** [Amna-Hassan04/Serenity-Guide#28]
hey @Amna-Hassan04  I would really liked to add a license file and also a documentation file containing the explanation of each line of code so it is easy to understand for developers

**Comment by priyanshaggarwal001** [comment]
I would also like to add one more file containing the template for GitHub issue so that who is resolving it will be easy to understand what type of issue it was and how it solved everything

**Comment by Amna-Hassan04** [comment]
sure, you can add the documentation dont make it very microscopic, I mean maybe dont explain every line of code, just write the main features and how we have implemented them in code etc. as for the template of github issue, raise a separate issue here and ask to add in some instructions like. problems screenshot, details, if someone is proposing a new feature they have to list down features properly also attach a screenshot of how the project should look like afterwards (can attach screenshot for any other project that has that functionality that they wanna implement). I will assign it to you. this issue template is important so consider working on this before I will assign you "task2" points for this one.

**Comment by priyanshaggarwal001** [comment]
hey @Amna-Hassan04  I have completed both the issues and put it in pr also just the review is left and one more thing if possible in pr could u add the tages for gssoc and everything .
I enjoyed the work and challenges and for the screenshot mandatory I have tried to put the workflow file which according to me is correct but might be having few bugs which I am not able to catch so It would be very helpful like u can assign someone else to check the code and do few changed
