### ISSUE TITLE
Github Issue Template

### ISSUE THREAD

**Issue by Amna-Hassan04** [Amna-Hassan04/Serenity-Guide#37]
Need to make a similar Issue template to the following one. both options should be there for new feature and bug fix etc. these details are provided in the link. 
https://github.com/recodehive/machine-learning-repos/issues/new/choose

**Comment by Amna-Hassan04** [comment]
@madhurik04 Please ask to be assigned this task and also, while making a pull request add the necessary screenshots.

**Comment by dsasa89** [comment]
i can do this task , if you can assingned it to me.

**Comment by dsasa89** [comment]
just give me simple explaination, so i can understand what exactly i want to do . thank you

**Comment by aryy8** [comment]
I can do this assign it to me

**Comment by Amna-Hassan04** [comment]
@dsasa89 @aryy8 Im assigning this task to both of you bcz this is important whoever gets this done first plz make a PR. I will merge the first working one I see,

**Comment by yasheela-alla** [comment]
Hi @Amna-Hassan04 , It's been more than 12hrs and the issue hasn't been fixed yet, can i work on it?

**Comment by Amna-Hassan04** [comment]
@yasheela-alla yes you can work on this.

**Comment by yasheela-alla** [comment]
Hey @Amna-Hassan04 Please assign me, I will raise a PR

**Comment by Amna-Hassan04** [comment]
@dsasa89 I have linked everything in the issue description. you could even pull the code from the relevant link that i provided.

**Comment by dsasa89** [comment]
Mam I make tamplate you can check my profile , actually I have submissions
in my college that why I am delayed

**Comment by dsasa89** [comment]
I wil do  this in 2-3 days

**Comment by yasheela-alla** [comment]
hey @dsasa89 this issue is closed few mins ago!

**Comment by dsasa89** [comment]
Ok, thanks.
