### ISSUE TITLE
Soothing Sounds Feature Fixes and Enhancements

### ISSUE THREAD

**Issue by Himanshi-m** [Amna-Hassan04/Serenity-Guide#5]
![image](https://github.com/user-attachments/assets/288c1122-7c9d-48c8-b563-a60e496c3e02)

1. The selected sound does not play when the "Play Sound" button is clicked. No sound plays upon clicking the button. 
2. We can add more sound options, like white noise, pink noise, Nature sounds etc
3. Adding sound controls like volume control and looping.
I would like to take on this issue. Please assign this issue to me.

**Comment by Amna-Hassan04** [comment]
Assigned u the task and please, do share a screenshot to show how the controls look, so i can tell if they look ok with the theme of the app. also record a short video of the working sound playing. 
Good Luck !

**Comment by Himanshi-m** [comment]
Alright! Working on it.

**Comment by Himanshi-m** [comment]
Hey! I've updated the tasks, you can check and tell me how do the controls look, For reference, here's the screen recording:

https://github.com/user-attachments/assets/befe5579-8bce-4cb3-b172-3a7c04f7ed6e

**Comment by alpha597** [comment]
i want to contribute for this issue
