### ISSUE TITLE
Feature: Add scroll to top button 

### ISSUE THREAD

**Issue by shubhagarwal1** [Amna-Hassan04/Serenity-Guide#61]
Websites blog page, currently do not have a scroll to top button which can we time taking for user when number of blogs increases on the page, i will add a scroll to top button on blogs page and dedicated blog page for improving user experiece
Hey @Amna-Hassan04  please assign this task to me

**Comment by Amna-Hassan04** [comment]
@shubhagarwal1 someone else has already implemented this. I just merged the PR.
