### ISSUE TITLE
Bug: No sound on playing the audio 

### ISSUE THREAD

**Issue by sanyadureja** [Amna-Hassan04/Serenity-Guide#62]
<img width="1015" alt="bug" src="https://github.com/user-attachments/assets/3f7b6ac5-cab0-41bc-a4c8-98447240b459">
Under calm down with soothing sounds, when choosing the sound to play, no audio is coming.

I would request you @Amna-Hassan04 to assign me this issue as a part of GSSoC Extd'24 along with all the appropriate labels. Looking forward to your response.

Thanks and Regards

**Comment by Amna-Hassan04** [comment]
@sanyadureja this was already fixed but is not deployed currently, the deployed version is old, please confirm if you are running the app locally and face this issue.

**Comment by sanyadureja** [comment]
@Amna-Hassan04 yes i'm facing this issue as it's not deployed it, so the changes aren't being reflected on the app.

**Comment by Amna-Hassan04** [comment]
@Amna-Hassan04 you have checked by running it locally right?

**Comment by sanyadureja** [comment]
@Amna-Hassan04 yes, I have checked by running it locally right.

**Comment by sanyadureja** [comment]
@Amna-Hassan04 Do you want me to help with it? Shall I contribute?

**Comment by Amna-Hassan04** [comment]
@sanyadureja ok you can start working on this

**Comment by sanyadureja** [comment]
@Amna-Hassan04 sure will start working, thank you.

**Comment by sanyadureja** [comment]
@Amna-Hassan04 
https://huggingface.co/spaces/AmnaHassan/SereniFi/discussions/1 Please check this link.

I've raised a PR to update the app.py in order to deploy the new version of Hugging Face Spaces. Please accept my PR, looking forward to getting it merged.
