### ISSUE TITLE
Bug: Calming sounds not playing in SereniFi Guide

### ISSUE THREAD

**Issue by Shravani-Saratkar** [Amna-Hassan04/Serenity-Guide#8]
Description: 
When I try to play any of the calming sounds, the audio does not start. The play button seems to be responsive, but no sound is emitted, even though the app's volume settings are correctly configured.

Steps to reproduce:

Open the SereniFi Guide app.
Navigate to "Calm Space".
Navigate to the "Soothing Sounds" section.
Select any sound and press play.
Observe that no sound is produced.

Expected behavior:
 When pressing the play button, the selected calming sound should begin playing.

Additional context:

The other sections, like meditations and breathing exercises, work as expected.
I am also interested in adding more soothing music to the app as a feature enhancement. It would be helpful if I could be assigned to this task as well.
![Screenshot 2024-10-01 195356](https://github.com/user-attachments/assets/5e78bd60-07aa-4717-98ef-ac67cca7ba39)

**Comment by Amna-Hassan04** [comment]
Someone else asked for this task before so I have assigned to them when they will complete it and if you feel that there should be more sounds added, then you can open an issue again and I will assign you the task.
