### ISSUE TITLE
Add a new game under "Mood-Boosting Mini Games"- The Simon Game Challenge

### ISSUE THREAD

**Issue by sanyadureja** [Amna-Hassan04/Serenity-Guide#80]
<img width="937" alt="Screenshot 2024-10-06 at 1 47 46 AM" src="https://github.com/user-attachments/assets/5c6f9b9f-498a-48da-94ea-1f869dc02b23">

As given in the screenshot, I'll add 1 more game made by me **(NOT A GOOGLE LINK)** know as "The Simon Game Challenge".

Description:
- Simon Game is a memory-based game implemented using HTML, CSS, JavaScript, and jQuery. 
- The game consists of a series of buttons with different colors and sounds. 
- The player must mimic a random sequence generated by the game by clicking the buttons in the correct order. 
- In addition, the game tracks the player's score by incrementing it with each successful round which is displayed on the screen, providing feedback and motivation.

Game Link: https://sanyadureja.github.io/Simon-Game-JavaScript-jQuery/

It's in progress. After a few changes, I'll add it to your website SereniFi.

**Comment by sanyadureja** [comment]
@Amna-Hassan04  If you find this idea suitable, please assign it to me as part of GSSoC'24 Extended along with all the appropriate labels. As a beginner in open source contributions, this would be a fantastic opportunity for me to contribute to your website.

I look forward to your positive response.
Thanks and Regards

**Comment by Amna-Hassan04** [comment]
@sanyadureja I love this Idea, I was planning to open this issue/feature request and assign a level 3 to someone who can really make a nice looking mini game. I have checked the games link that you sent me, It does have some bugs, and you will need to add text elements to explain the game mechanic, plus this is a python based project dont you think you should make a game in python similar to this one and embed it in the page, we can a separate page for that in this project.

**Comment by sanyadureja** [comment]
@Amna-Hassan04 thank you so much for appreciating my idea and assigning it to me. 

Yes I'll resolve the bugs and add text elements too. Once I'm done with that I'll share with you and if that looks great, them simultaneously I'll try to make a separate page for the game on the website.

**Comment by sanyadureja** [comment]
@Amna-Hassan04 confirm me once do you want me to embed this game there itself along with other games or add an entirely new page for this?

**Comment by sanyadureja** [comment]
> @Amna-Hassan04 confirm me once do you want me to embed this game there itself along with other games or add an entirely new page for this?

Please update me on this as well so that I'll work accordingly.

**Comment by Amna-Hassan04** [comment]
@sanyadureja I wanted to embed the game in the page but it should look really good with the website's aesthetics and feel. if you have a game sample like that do showcase it here then we can decide.

**Comment by sanyadureja** [comment]
> @sanyadureja I wanted to embed the game in the page but it should look really good with the website's aesthetics and feel. if you have a game sample like that do showcase it here then we can decide.

sure, will revert soon.

**Comment by sanyadureja** [comment]
@Amna-Hassan04 I would like to try out pair programming with @ChitteshKumar in order to complete this issue as I'm facing certain issues and would like to explore more ideas.

Can you please guide us with the process.
@sanjay-kv you also help us with the same.

**Comment by sanyadureja** [comment]
@Amna-Hassan04 I've added my game in the way shown in the video. 

Embedding the game using i-frame is facing some issues due to Streamlit's limitations

https://github.com/user-attachments/assets/a2afc401-11f5-4589-87f8-fa2ed990574f

. Moreover this is looking much better, more people can add additional games like this too (with description and instructions). Please have a look at the video.

Now, I've raised my PR #172 , looking forward to getting it merged, please add all the necessary labels(GSSOC-EXT, Hacktoberfest and the level)

**Comment by sanyadureja** [comment]
@Amna-Hassan04 I've raised my PR https://github.com/Amna-Hassan04/Serenity-Guide/pull/172 , looking forward to getting it merged.
