### ISSUE TITLE
Issues in Readme file (in installation)

### ISSUE THREAD

**Issue by sindhuja184** [Amna-Hassan04/Serenity-Guide#82]
In the step-3 of installations, the dependencies are not mentioned.
![image](https://github.com/user-attachments/assets/3f873a19-bbc3-4ca8-96ef-11ffaf7b4f67)
It simply states pip install

@Amna-Hassan04, please assign the task I would be glad to add those dependencies.

Thanks

**Comment by Amna-Hassan04** [comment]
doesnt pip install all the required libraries in a project.
