### ISSUE TITLE
Implement a Welcome Popup to Greet Users by Name

### ISSUE THREAD

**Issue by leharikasri** [Amna-Hassan04/Serenity-Guide#92]
I would like to implement a welcome popup that enhances user interaction by greeting users with their name. The popup should perform the following functions:

Username Input:

Display a text input field for users to enter their username.
Ensure the input field is clearly labeled and accessible.
Welcome Message:

Upon submission of the username, the app should display a welcome message in the format: "Welcome, <username>!".

**Comment by Amna-Hassan04** [comment]
this feature might be good for future but rigth now this would just make unnecessary clutter in the app.

**Comment by leharikasri** [comment]
ok
