### ISSUE TITLE
GO to Top Button Not working

### ISSUE THREAD

**Issue by Amna-Hassan04** [Amna-Hassan04/Serenity-Guide#94]
![image](https://github.com/user-attachments/assets/c0c3595a-961b-4121-b6c6-82d5deab126c)
When you click Top we do not go automatically to the page of the page Whoever solves this should attach a video recording of thsi working in the PR.

**Comment by Harshitraaaj** [comment]
Assign this role to me , I can fix this issue

**Comment by Harshitraaaj** [comment]
fixed , now in calm space page top feature is working .Here is the working 

video_link  : https://drive.google.com/file/d/1yQqckRsYTFqeE9g7KKpmXkgMDvB_2kMV/view?usp=drivesdk

can i generate  pull req
