### ISSUE TITLE
GIF alignment should be in a bit centre  

### ISSUE THREAD

**Issue by RudraKumarSharma** [Amna-Hassan04/Serenity-Guide#97]
This breathing girl GIF should be in a little centre so that the whole page look symmetrical.

![Screenshot 2024-10-08 at 12 03 53 PM](https://github.com/user-attachments/assets/d6b54688-4810-4550-9fb0-a47efdfa8281)

@Amna-Hassan04  Please assign me this task i would like to fix this

**Comment by Amna-Hassan04** [comment]
@RudraKumarSharma someone is already on the task to make the tip appear next to the gif.
