### ISSUE TITLE
Add some music and toggle dark mode option

### ISSUE THREAD

**Issue by 23wh1a0513** [Amna-Hassan04/Serenity-Guide#99]
I think i would be better if they add some music when entered or open this mind-relaxing application.It is necessary add music according
to their mood like gitar,violin,nature sounds etc.And also add dark mode option.

**Comment by 23wh1a0513** [comment]
Is the work assigned to me

**Comment by Amna-Hassan04** [comment]
@23wh1a0513 I think someone else is already working on this, plz check teh issue section and re confirm that no one else is working on this first

**Comment by 23wh1a0513** [comment]
@Amna-Hassan04 Yes, i checked it someone is working on toggle dark mode but i want add a pleasant sound effect every time user open this application(website)

**Comment by Amna-Hassan04** [comment]
@23wh1a0513 we already have music integrated in the app we even have spotify playlists now, so this isnt something that I have planned for rigth now.
